### PR TITLE
Add default implemenation of cors policy using environment configuration

### PR DESCRIPTION
**Pull request by RumataEstor**

### CODE REVIEW

**Comment by danielwhite** [comment]
Test suite is failing on R15. Not sure if it's worth continuing support for it.

**Comment by danielwhite** [comment]
Do we still need to check for callbacks to be exported with this change? 

See: https://github.com/danielwhite/cowboy_cors/blob/master/src/cowboy_cors.erl#L193

**Comment by RumataEstor** [comment]
This is only a default implementation that is not used if you specify your own. So the checks have to stay to not break existing users.

**Comment by danielwhite** [comment]
Cool. Looks good to me.

**Pull request merged**
